// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ITBHNBpW0y--F63fsBkJkmYbjO_wWNU',
    appId: '1:103810845853:web:6eccd06816500ad2785874',
    messagingSenderId: '103810845853',
    projectId: 'flutter-2025-3a6dd',
    authDomain: 'flutter-2025-3a6dd.firebaseapp.com',
    storageBucket: 'flutter-2025-3a6dd.firebasestorage.app',
    measurementId: 'G-C95T7F13MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxMbq30V3AjkphxbdEHczxBcvInO-kHMI',
    appId: '1:103810845853:android:758694a55f1e130f785874',
    messagingSenderId: '103810845853',
    projectId: 'flutter-2025-3a6dd',
    storageBucket: 'flutter-2025-3a6dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk9YcVg91jDdRahn76WEE0wZmb6KV0Qbc',
    appId: '1:103810845853:ios:ea2237203b763674785874',
    messagingSenderId: '103810845853',
    projectId: 'flutter-2025-3a6dd',
    storageBucket: 'flutter-2025-3a6dd.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk9YcVg91jDdRahn76WEE0wZmb6KV0Qbc',
    appId: '1:103810845853:ios:ea2237203b763674785874',
    messagingSenderId: '103810845853',
    projectId: 'flutter-2025-3a6dd',
    storageBucket: 'flutter-2025-3a6dd.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5ITBHNBpW0y--F63fsBkJkmYbjO_wWNU',
    appId: '1:103810845853:web:69bb9ba4c69a5d1a785874',
    messagingSenderId: '103810845853',
    projectId: 'flutter-2025-3a6dd',
    authDomain: 'flutter-2025-3a6dd.firebaseapp.com',
    storageBucket: 'flutter-2025-3a6dd.firebasestorage.app',
    measurementId: 'G-ME80SWLV7G',
  );

}